#!/bin/sh

# Need proper urlencode here.
# For now just replace spaces with +
query=$(sed 's/ /+/g' <<<"$1")



for url in \
"https://mail.google.com/mail/u/0/#search/$query'" \
"https://www.economist.com/search?q=$query" \
"https://www.ft.com/search?q=$query" \
"https://www.nytimes.com/search?query=$query" \
"https://www.wsj.com/search?query=$query" \
"https://www.washingtonpost.com/newssearch/?query=$query" \
"https://www.theatlantic.com/search/?q=$query" \
"https://www.newyorker.com/search/q/$query" \
"https://foreignpolicy.com/?s=$query" \
"https://www.foreignaffairs.com/search/$query" \
"https://www.prospectmagazine.co.uk/search?q=$query" \
;do
  open $url
done
